version: "3.8"

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./services/frontend/build
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5000
    depends_on:
      - backend
