version: "3.8"

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5000
    # depends_on:
    #   - backend

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - 5001:5000
