version: "3.8"

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5000
    image: frontend-address-book

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    image: backend-address-book
    volumes:
      - ~/.aws:/root/.aws
    depends_on:
      frontend:
        condition: service_completed_successfully
